CREATE TABLE DEV_AUD_CERNER.int_orders(
 order_number int NOT NULL,
 order_date date NOT NULL,
 cust_id int NOT NULL,
 salesperson_id int NOT NULL,
 amount float NOT NULL
) ;

INSERT INTO DEV_AUD_CERNER.int_orders (order_number, order_date, cust_id, salesperson_id, amount) VALUES (30, TO_DATE('1995-07-14','YYYY-MM-DD'), 9, 1, 460);
INSERT INTO DEV_AUD_CERNER.int_orders (order_number, order_date, cust_id, salesperson_id, amount) VALUES (10, TO_DATE('1996-08-02','YYYY-MM-DD'), 4, 2, 540);
INSERT INTO DEV_AUD_CERNER.int_orders (order_number, order_date, cust_id, salesperson_id, amount) VALUES (40, TO_DATE('1998-01-29','YYYY-MM-DD'), 7, 2, 2400);
INSERT INTO DEV_AUD_CERNER.int_orders (order_number, order_date, cust_id, salesperson_id, amount) VALUES (50, TO_DATE('1998-02-03','YYYY-MM-DD'), 6, 7, 600);
INSERT INTO DEV_AUD_CERNER.int_orders (order_number, order_date, cust_id, salesperson_id, amount) VALUES (60, TO_DATE('1998-03-02','YYYY-MM-DD'), 6, 7, 720);
INSERT INTO DEV_AUD_CERNER.int_orders (order_number, order_date, cust_id, salesperson_id, amount) VALUES (70, TO_DATE('1998-05-06','YYYY-MM-DD'), 9, 7, 150);
INSERT INTO DEV_AUD_CERNER.int_orders (order_number, order_date, cust_id, salesperson_id, amount) VALUES (20, TO_DATE('1999-01-30','YYYY-MM-DD'), 4, 8, 1800);



SELECT *fROM DEV_AUD_CERNER.int_orders;

SELECT SUM(AMOUNT) FROM DEV_AUD_CERNER.int_orders;

SELECT SALESPERSON_ID,SUM(AMOUNT) FROM DEV_AUD_CERNER.int_orders
GROUP BY SALESPERSON_ID;

--WINDOW ON COMPLETE TABLE

SELECT ORDER_NUMBER,ORDER_DATE,CUST_ID,SALESPERSON_ID,AMOUNT,SUM(AMOUNT) OVER() FROM 
DEV_AUD_CERNER.int_orders;

-- SUM FOR EVERY PARTITION

SELECT ORDER_NUMBER,ORDER_DATE,CUST_ID,SALESPERSON_ID,AMOUNT,SUM(AMOUNT) OVER(PARTITION BY SALESPERSON_ID) AS SN FROM 
DEV_AUD_CERNER.int_orders;

--RUNNING SUM (FOR FULL TABLE)

SELECT ORDER_NUMBER,ORDER_DATE,CUST_ID,SALESPERSON_ID,AMOUNT,SUM(AMOUNT) OVER(ORDER BY ORDER_DATE) AS SN FROM 
DEV_AUD_CERNER.int_orders;

--RUNNING SUM (FOR EVERY PARTITION)

SELECT ORDER_NUMBER,ORDER_DATE,CUST_ID,SALESPERSON_ID,AMOUNT,SUM(AMOUNT) OVER(PARTITION BY SALESPERSON_ID ORDER BY ORDER_DATE) AS SN FROM 
DEV_AUD_CERNER.int_orders;

-- SUM OF PREVIOUS 2 ROWW AND CURRENT ROW
SELECT ORDER_NUMBER,ORDER_DATE,CUST_ID,SALESPERSON_ID,AMOUNT,SUM(AMOUNT) OVER(ORDER BY ORDER_DATE ROWS BETWEEN 2 PRECEDING  AND CURRENT ROW) AS SN FROM 
DEV_AUD_CERNER.int_orders;

-- SUM OF PREVIOUS 1 PREVIOUS ROW AND ONE FOLLOWING ROW ( AS WE ARE DOING BETWEEN CURRENT ROW WILL ALWAYS BE THERE)

SELECT ORDER_NUMBER,ORDER_DATE,CUST_ID,SALESPERSON_ID,AMOUNT,SUM(AMOUNT) OVER(ORDER BY ORDER_DATE ROWS BETWEEN 1 PRECEDING  AND 1 FOLLOWING) AS SN FROM 
DEV_AUD_CERNER.int_orders;


-- SUM OF ALL PREVIOUS ROWS AND CURRENT ROW 

SELECT ORDER_NUMBER,ORDER_DATE,CUST_ID,SALESPERSON_ID,AMOUNT,SUM(AMOUNT) OVER(ORDER BY ORDER_DATE ROWS BETWEEN UNBOUNDED PRECEDING  AND CURRENT ROW) AS SN FROM 
DEV_AUD_CERNER.int_orders;


-- SUM OF ALL PREVIOUS ROWS AND CURRENT ROW WITHIN EACH SALESPERSON_ID

SELECT ORDER_NUMBER,ORDER_DATE,CUST_ID,SALESPERSON_ID,AMOUNT,SUM(AMOUNT) OVER(PARTITION BY SALESPERSON_ID ORDER BY ORDER_DATE ROWS BETWEEN UNBOUNDED PRECEDING  AND CURRENT ROW) AS SN FROM 
DEV_AUD_CERNER.int_orders;

--LEAD

SELECT ORDER_NUMBER,ORDER_DATE,CUST_ID,SALESPERSON_ID,AMOUNT,SUM(AMOUNT) OVER(ORDER BY ORDER_DATE ROWS BETWEEN 1 PRECEDING  AND 1 PRECEDING) AS SN FROM 
DEV_AUD_CERNER.int_orders;

--LAG

SELECT ORDER_NUMBER,ORDER_DATE,CUST_ID,SALESPERSON_ID,AMOUNT,SUM(AMOUNT) OVER(ORDER BY ORDER_DATE ROWS BETWEEN 1 FOLLOWING  AND 1 FOLLOWING) AS SN FROM 
DEV_AUD_CERNER.int_orders;




