--1) STRING VERTICALLY

WITH VERTICALLY (COLN) AS
(SELECT 'K I R A N' FROM DUAL)
 SELECT REGEXP_SUBSTR(COLN, '[^ ]+', 1, LEVEL) VAL
FROM VERTICALLY
CONNECT BY LEVEL <= REGEXP_COUNT(COLN, ' ') + 1;

SELECT SUBSTR ('KIRAN', LEVEL, 1) FROM DUAL CONNECT BY LEVEL <= LENGTH ('KIRAN');

--2) HOW TO DISPLAY 1 TO 100 NUMBERS WITH QUERY?

SELECT LEVEL FROM DUAL CONNECT BY LEVEL <=100;

--3) HOW TO REMOVE DUPLICATE ROWS FROM TABLE?

--ONE WAY

DELETE FROM EMPPLOYEE
WHERE ROWID NOT IN
(SELECT MAX(ROWID) FROM EMPPLOYEE GROUP BY ID);

--SECOND WAY

DELETE FROM EMPPLOYEE WHERE ROWID IN
               (
                 SELECT RID FROM
                  (
                    SELECT ROWID RID,
                      ROW_NUMBER() OVER(PARTITION BY ID ORDER BY ID) RN
                      FROM EMPPLOYEE
                  )
                WHERE RN > 1
               );
			   

-- THIRD WAY

DELETE FROM EMPPLOYEE E1
         WHERE ROWID NOT IN
          (SELECT MAX(ROWID) FROM EMPPLOYEE E2
           WHERE E1.ID = E2.ID );

-- IMP AND EASY WAY---

with cte as (SELECT t.*,row_number() over(partition by emp_id order by emp_id desc)as rn from t3 t)
DELETE from cte where rn>1;

select *From (
SELECT t.*,row_number() over(partition by emp_id order by emp_id desc)as rn from t3 t
 )where rn>1
		   
--4) COUNT OF DUPLICATE ROWS

SELECT ID,COUNT(ID) FROM TABLETWO
GROUP BY ID
HAVING COUNT(ID) > 1
ORDER BY COUNT(ID) DESC

--5) HOW TO FIND THIRD HIGHEST SALARY IN EMPLOYEE TABLE USING SELF-JOIN?

--USING SELF-JOIN

SELECT *
FROM TABLETWO E1
WHERE (SELECT COUNT(DISTINCT E2.SALARY) FROM TABLETWO E2 WHERE E2.SALARY >= E1.SALARY) = 3

--USING DENSE_RANK

SELECT *FROM (
SELECT ID,SALARY,DENSE_RANK() OVER(ORDER BY SALARY DESC) AS RN FROM TABLETWO
)WHERE RN=2

-- TO GET COMPLETE RECORD

SELECT *FROM (
SELECT E.*,DENSE_RANK() OVER(ORDER BY SALARY DESC) AS RN FROM TABLETWO E
)WHERE RN = 2;

-- TO GET TOP 3 SALARY RECORDS
SELECT *FROM (
SELECT E.*,DENSE_RANK() OVER(ORDER BY SALARY DESC) AS RN FROM TABLETWO E
)WHERE RN BETWEEN 1 AND 3

--6) DISPLAY BOTH MIN AND MAX SALARY SAMETIME

SELECT MAX(SALARY) FROM TABLETWO
UNION 
SELECT MIN(SALARY) FROM TABLETWO

--7) HOW TO DISPLAY FOLLOWING USING QUERY?

*
* *
* * *
* * * *

SELECT LPAD (‘*’, ROWNUM,’*’) FROM STUDENT WHERE ROWNUM <4;


--7) IF MARKS COLUMN CONTAIN THE COMMA SEPARATED VALUES FROM STUDENT TABLE. HOW TO CALCULATE THE COUNT OF THAT COMMA SEPARATED VALUES?

SELECT ID, REGEXP_COUNT(MARKS,',') AS COUNT FROM TABLETWO;

--8)HOW TO CREATE THE STUDENT_1 TABLE, WHICH IS EXACT REPLICA OF STUDENT TABLE?

CREATE TABLE TABLETHREE AS SELECT * FROM TABLETWO;

--9) CALCULATE NO OF WEEKDAYS IN A MONTH

SELECT SUM(CASE WHEN TO_CHAR(DT, 'FMDAY') IN ('SATURDAY', 'SUNDAY') THEN 0
                   ELSE 1
              END) NO_OF_WORKING_DAYS
   FROM (SELECT TO_DATE('01-'||'DEC'||'-2021', 'DD-MON-YYYY')+LEVEL-1 DT
         FROM DUAL
         CONNECT BY LEVEL <= LAST_DAY(TO_DATE('01-'||'DEC'||'-2021', 'DD-MON-YYYY')) - TO_DATE('01-'||'DEC'||'-2021', 'DD-MON-YYYY') +1
        )
		
--10) HOW TO DISPLAY DATE IN DD-MON-YYYY TABLE?

SELECT TO_DATE (ORDER_DATE,’DD-MON-YYYY’) DATE_FORMAT FROM ORDERS;

--11) CALCULATE NO OF WEEKENDS IN A MONTH

WITH THIS_MONTH AS (
SELECT TRUNC (SYSDATE, 'MM')+LEVEL - 1 AS CDATE
FROM DUAL
CONNECT BY LEVEL <= LAST_DAY (TRUNC(SYSDATE,'MM')) - TRUNC(SYSDATE, 'MM') + 1)
SELECT COUNT(CDATE) AS TOTALWEEKENDS
FROM THIS_MONTH
WHERE TRIM(TO_CHAR(CDATE, 'DAY')) IN ('SATURDAY', 'SUNDAY');


--12) WHAT IS QUERY TO FETCH LAST DAY OF PREVIOUS MONTH IN ORACLE?

SELECT LAST_DAY(ADD_MONTHS SYSDATE,-1)) FROM DUAL;

--13) WRITE QUERY TO FIND THE REPEATED CHARACTERS FROM YOUR NAME?

SELECT REGEXP_COUNT('KIRANKUMAR','K') AS REPEATED_CHARACTER FROM DUAL;

--14) HOW TO DISPLAY DEPARTMENTWISE AND MONTHWISE MAXIMUM SALARY?

SELECT DNO, TO_CHAR (JDATE,'MON') AS MONTH FROM EMP GROUP BY DNO, TO_CHAR(JDATE,'MON');

--15) TO GET NTH RECORD FROM ORACLE TABLE

SELECT *FROM (
SELECT ROWNUM AS RN,E.* FROM TABLETWO E
)WHERE RN=2;

--15) DISPLAY 4 TO 7 RECORDS FROM EMPLOYEE TABLE.

SELECT *FROM (
SELECT ROWNUM AS RN,E.* FROM TABLETWO E
)WHERE RN BETWEEN 4 AND 7;


--16) WHAT IS QUERY TO FETCH LAST RECORD OF TABLE?

SELECT *FROM TABLETWO WHERE ROWID=(SELECT MAX(ROWID) FROM TABLETWO);


--17) HOW TO CALCULATE NUMBER OF ROWS IN TABLE WITHOUT USING COUNT FUNCTION?

SELECT TABLE_NAME, NUM_ROWS FROM USER_TABLES WHERE TABLE_NAME='TABLETWO';


--18) How to get DDL of table in Oracle?



--19) How to get distinct records from the table without using distinct keyword.

1) UNION 

	SELECT *FROM TABLETWO
	UNION 
	SELECT *fROM TABLETWO
	
2) GROUP BY

	SELECT ID,NAME
	FROM TABLETWO
	GROUP BY ID,NAME
	
3) INTERSECT

	SELECT *FROM TABLETWO
	INTERSECT
	SELECT *FROM TABLETWO
	
--20) How Can i create table with same structure of Employee table?

Create table TABLET as Select * from TABLETWO where 1=2;

--21) How Can i create table with same structure of Employee table WITH DATA?


Create table TABLET as Select * from TABLETWO where 1=1;

--22) Display odd records

SELECT *FROM (
SELECT E.*,ROWNUM AS RN FROM TABLETWO E
)WHERE Mod(RN,2)=1;

--23) display even records

SELECT *FROM (
SELECT E.*,ROWNUM AS RN FROM TABLETWO E
)WHERE Mod(RN,2)=0;


CREATE TABLE T1 (ID INT);
CREATE TABLE T2 (ID INT);
INSERT INTO T1 VALUES (1);
INSERT INTO T1 VALUES (1);
INSERT INTO T1 VALUES (1);
INSERT INTO T1 VALUES (2);

INSERT INTO T2 VALUES (1);
INSERT INTO T2 VALUES (1);
INSERT INTO T2 VALUES (1);
INSERT INTO T2 VALUES (1);
INSERT INTO T2 VALUES (2);

COMMIT;

SELECT T1.ID,T2.ID FROM T1
FULL JOIN T2 ON T1.ID = T2.ID;

SELECT T1.ID,T2.ID FROM T1
CROSS JOIN T2

----------DEPT WISE AVG SALARY------------

--where - scan each record and filter the records
-- having - will be applied to each group ( filtering on aggregated results)

CREATE TABLE T3 (ID INT,DEPT_ID INT,SALARY INT);

INSERT INTO T3 VALUES (1,100,10000);
INSERT INTO T3 VALUES (2,100,20000);
INSERT INTO T3 VALUES (3,100,12000);

INSERT INTO T3 VALUES (4,200,12000);
INSERT INTO T3 VALUES (5,200,1000);
INSERT INTO T3 VALUES (6,300,100);

COMMIT;

SELECT *fROM T3;

SELECT DEPT_ID,AVG(SALARY)
FROM T3
WHERE SALARY > 100
GROUP BY DEPT_ID
HAVING AVG(SALARY) > 10000

-------- rows to columns and columns to rows ------------

CREATE TABLE T3 (EMP_ID INT,TYPE VARCHAR(20),VALUE INT);

INSERT INTO T3 VALUES (1,'salary',10000);
INSERT INTO T3 VALUES (1,'bonus',5000);
INSERT INTO T3 VALUES (1,'hike',10);

INSERT INTO T3 VALUES (2,'salary',20000);
INSERT INTO T3 VALUES (2,'bonus',2000);
INSERT INTO T3 VALUES (2,'hike',20);

INSERT INTO T3 VALUES (3,'salary',30000);
INSERT INTO T3 VALUES (3,'bonus',3000);
INSERT INTO T3 VALUES (3,'hike',30);

COMMIT;

SELECT *fROM T3;

---Pivot---

SELECT EMP_ID,
SUM(CASE WHEN TYPE='salary' THEN VALUE  END) AS SALARY,
SUM(CASE WHEN TYPE='bonus' THEN VALUE  END) AS BONUS,
SUM(CASE WHEN TYPE='hike' THEN VALUE  END) AS HIKE
FROM T3
GROUP BY EMP_ID
ORDER BY 1;

--Unpivot---
create table t3_new as
SELECT EMP_ID,
SUM(CASE WHEN TYPE='salary' THEN VALUE  END) AS SALARY,
SUM(CASE WHEN TYPE='bonus' THEN VALUE  END) AS BONUS,
SUM(CASE WHEN TYPE='hike' THEN VALUE  END) AS HIKE
FROM T3
GROUP BY EMP_ID
ORDER BY 1;

select *from t3_new;

select emp_id,'salary' as type ,salary as value from T3_NEW
union all
select emp_id,'bonus' as type ,bonus as value from t3_new
union all
select emp_id,'hike' as type , bonus as value from t3_new

--DROP TABLE T3;


-----delete duplicates from table--------

with cte as (SELECT t.*,row_number() over(partition by emp_id order by emp_id desc)as rn from t3 t)
DELETE from cte where rn>1;

select *From (
SELECT t.*,row_number() over(partition by emp_id order by emp_id desc)as rn from t3 t
 )where rn>1
 
---- SECOND HIGHEST SALARY FROM EACH DEPT----

CREATE TABLE T4 (ID INT,DEPT_ID INT,SALARY INT);

INSERT INTO T4 VALUES (1,100,10000);
INSERT INTO T4 VALUES (2,100,20000);
INSERT INTO T4 VALUES (3,100,12000);
             
INSERT INTO T4 VALUES (4,200,12000);
INSERT INTO T4 VALUES (5,200,1000);
INSERT INTO T4 VALUES (6,300,100);

COMMIT;

SELECT *fROM T4;

SELECT *fROM (
SELECT E.*,DENSE_RANK() OVER(PARTITION BY DEPT_ID ORDER BY SALARY DESC) AS RN FROM T4 E
)WHERE RN=2

-----------Find all transactions done by shilpa------------

CREATE TABLE T4 (ID INT,NAME VARCHAR(20),DEPT_ID INT,SALARY INT);

INSERT INTO T4 VALUES (1,'Shilpa',100,10000);
INSERT INTO T4 VALUES (2,'SHILPA'100,20000);
INSERT INTO T4 VALUES (3,'shilpa',100,12000);
INSERT INTO T4 VALUES (4,'Mike',100,12000);
             


COMMIT;

SELECT *fROM T4;


SELECT *FROM T4
WHERE UPPER(NAME) = 'SHILPA'

----UPDATE Query to swap gender------

CREATE TABLE T4 (ID INT,NAME VARCHAR(20),DEPT_ID INT,SALARY INT,GENDER VARCHAR(20));

INSERT INTO T4 VALUES (1,'Shilpa',100,10000,'Male');
INSERT INTO T4 VALUES (2,'Mary',100,20000,'Male');
INSERT INTO T4 VALUES (3,'Mike',100,12000,'Female');
INSERT INTO T4 VALUES (4,'James',100,12000,'Female');
             


COMMIT;

SELECT *fROM T4;

UPDATE T4
SET GENDER= CASE WHEN GENDER='Male' then 'Female'
                 WHEN GENDER='Female' then 'Male' end


---- employess salary more than his manager----------

CREATE TABLE T4 (ID INT,NAME VARCHAR(20),DEPT_ID INT,SALARY INT,GENDER VARCHAR(20),MANAGER_ID INT);

INSERT INTO T4 VALUES (1,'Ankit',100,10000,'Male',4);
INSERT INTO T4 VALUES (2,'Mohit',100,15000,'Male',5);
INSERT INTO T4 VALUES (3,'Vikas',100,10000,'Female',4);
INSERT INTO T4 VALUES (4,'Rohit',100,5000,'Female',2);
INSERT INTO T4 VALUES (5,'Mudit',100,12000,'Male',6);
INSERT INTO T4 VALUES (6,'Agam',100,12000,'Male',2);
INSERT INTO T4 VALUES (7,'Sanjay',100,9000,'Female',2);
INSERT INTO T4 VALUES (8,'Asish',100,5000,'Female',2);
             


COMMIT;

SELECT *fROM T4;

SELECT EMP.NAME ,MGR.NAME AS MANAGER_NAME FROM T4 EMP
INNER JOIN T4 MGR ON EMP.MANAGER_ID=MGR.ID
WHERE EMP.SALARY > MGR.SALARY


-----Custom sort----
select *from customers
order by case when countryName='India' then 0 else 1 end, countryName

---Generate numbers using recrsive CTE--------

CTE running in a loop.

CTE will itself and run till its breakpoint.

with cte (num) as (
select 1 as num -- anchor query

union ALL

select num+1 as num -- recursive query
from cte_numbers
where num<6 -- filter to stop the recursion
)
select num 
from cte_numbers

1
2
3
4
5
6
