CREATE TABLE TABLEONE (
ID INT,
DESCRIPTION VARCHAR2(30)
);


CREATE TABLE TABLETWO (
ID INT,
DESCRIPTION VARCHAR2(30)
);


INSERT INTO TABLEONE VALUES (1,'TEST1');
INSERT INTO TABLEONE VALUES (2,'TEST2');
INSERT INTO TABLEONE VALUES (3,'TEST3');
INSERT INTO TABLEONE VALUES (4,'TEST4');
INSERT INTO TABLEONE VALUES (5,'TEST5');
INSERT INTO TABLEONE VALUES (6,'TEST11');

COMMIT;

SELECT *FROM TABLEONE;


INSERT INTO TABLETWO VALUES (1,'TEST6');
INSERT INTO TABLETWO VALUES (2,'TEST7');
INSERT INTO TABLETWO VALUES (3,'TEST8');
INSERT INTO TABLETWO VALUES (4,'TEST9');
INSERT INTO TABLETWO VALUES (5,'TEST10');
INSERT INTO TABLETWO VALUES (7,'TEST12');

--INNER

SELECT *FROM TABLEONE A
INNER JOIN TABLETWO B ON A.ID = B.ID;

--LEFT
SELECT *FROM TABLEONE A
LEFT JOIN TABLETWO B ON A.ID = B.ID;

--RIGHT
SELECT *FROM TABLEONE A
RIGHT JOIN TABLETWO B ON A.ID = B.ID;

--FULL
SELECT *FROM TABLEONE A
FULL JOIN TABLETWO B ON A.ID = B.ID;

-- RECORDS FROM TABLEONE , WHICH ARE NOT THERE IN TABLETW0

SELECT *FROM TABLEONE A
LEFT JOIN TABLETWO B ON A.ID = B.ID
WHERE B.ID IS NULL;

-- RECORDS FROM TABLETWO, WHICH ARE NOT THERE IN TABLEONE
SELECT *FROM TABLEONE A
RIGHT JOIN TABLETWO B ON A.ID = B.ID
WHERE A.ID IS NULL;

-- RECORDS WHICH ARE UNIQUE TO BOTH TABLES
SELECT *FROM TABLEONE A
FULL JOIN TABLETWO B ON A.ID = B.ID
WHERE A.ID IS NULL OR B.ID IS NULL;

OR

SELECT *FROM TABLEA
MINUS/INTERSECT
SELECT *FROM TABLEB

-- CARTESIAN JOIN

SELECT *FROM TABLEONE A
INNER JOIN TABLETWO B ON 1=1;

--
SELECT *FROM TABLEONE NATURAL JOIN TABLETWO

===================
LEFT JOIN
===================

SELECT *FROM EMP
LEFT JOIN DEPT ON EMP.EMP_ID = DEP.DEP_ID AND DEP.DEPT_NAME = 'Analytics'

here all records from emp will be retreived and then and clause will be applied then the join

SELECT *FROM EMP
LEFT JOIN DEPT ON EMP.EMP_ID = DEP.DEP_ID 
WHERE DEP.DEPT_NAME = 'Analytics'

there join will be performed first and then the where clause will be applied.